spring:
  output:
    ansi:
      enabled: ALWAYS
security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: e5dd6150538185c4fa9550b60a6f9977
          redirect-uri: "http://localhost:8080/katalk/callback"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope: profile_nickname, account_email #동의 항목
          client-name: Kakao
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id